### ISSUE TITLE
Add  base react hello world application

### ISSUE THREAD

**Issue by Sfitzg** [markmacey/poc1#1]
Hey @markmacey 

_I'm  trying to mess around with git and github abit to learn and have some fun._

I propose adding a base React application (Hello World) using [Create React App](https://reactjs.org/docs/create-a-new-react-app.html) to the `poc1` repo and amending the `README.md` with instructions in the documentation on how to spin it up in a local dev environment.

then once the this is added you can try the process in the documentation to see if you can spin it up on your side 
will be a fun little exercise. 

Let me know if you Happy with this and I will create a pull request with the amendments 

Cheers Shaun

**Comment by markmacey** [comment]
Hey Shaun,
Yes I think this is a great idea, go ahead and make the changes, then let me know when you're done.
I would like to see the React UI working, and maybe we can hook it into a Python API service,
Mark

**Comment by Sfitzg** [comment]
Hey @markmacey,

Ok I have created a pull request with the vanila react application and updated 'readme.md'
I put  the react application into the '/frontend' folder so we can put a api in the '/backend' folder at a later stage. 

Go into the  pull request and merge it into the master branch and then see if you can get it running on your local machine 

Cheers Shaun
